services:
  localstack:
    image: localstack/localstack:3.0.2
    container_name: farming-grants-agreements-pdf-localstack
    ports:
      - '4568:4566' # LocalStack Gateway (PDF)
      - '4610-4659:4610-4659' # external services port range (PDF)
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/farming-grants-agreements-pdf-localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  farming-grants-agreements-pdf:
    build:
      context: .
      target: development
    ports:
      - '3556:3556'
    links:
      - 'localstack:localstack'
    depends_on:
      localstack:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3556
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://host.docker.internal:4566
      SQS_ENDPOINT: http://host.docker.internal:4566
      QUEUE_URL: http://host.docker.internal:4566/000000000000/create_agreement_pdf
      QUEUE_NAME: create_agreement_pdf
      SNS_ENDPOINT: http://host.docker.internal:4566
      SNS_TOPIC_TYPE_AGREEMENT_STATUS_UPDATED: io.onsite.agreement.status.updated
      SNS_TOPIC_ARN_AGREEMENT_STATUS_UPDATED: arn:aws:sns:eu-west-2:000000000000:agreement_status_updated
      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: farming-grants-agreements-pdf-bucket
      FILES_S3_BASE_TERM_PREFIX: ${FILES_S3_BASE_TERM_PREFIX:-base}
      FILES_S3_EXTENDED_TERM_PREFIX: ${FILES_S3_EXTENDED_TERM_PREFIX:-extended}
      FILES_S3_MAXIMUM_TERM_PREFIX: ${FILES_S3_MAXIMUM_TERM_PREFIX:-maximum}
      FILES_S3_BASE_TERM_THRESHOLD: ${FILES_S3_BASE_TERM_THRESHOLD:-10}
      FILES_S3_EXTENDED_TERM_THRESHOLD: ${FILES_S3_EXTENDED_TERM_THRESHOLD:-15}
      FILES_S3_MAXIMUM_TERM_THRESHOLD: ${FILES_S3_MAXIMUM_TERM_THRESHOLD:-20}
      FILES_S3_RETENTION_BASE_YEARS: ${FILES_S3_RETENTION_BASE_YEARS:-7}
      JWT_ENABLED: ${JWT_ENABLED:-true}
      AGREEMENTS_JWT_SECRET: ${AGREEMENTS_JWT_SECRET:-a-string-secret-at-least-256-bits-long}
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      TMP_PDF_FOLDER: /var/tmp/defra-pdf
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
